package net.javaguides.Banking_app.entity;
// ↑ Belongs to the "entity" package — entities represent database tables.

import jakarta.persistence.*;
// ↑ Imports all JPA annotations (Entity, Table, Id, Column, etc.)

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
// ↑ Lombok: auto-generates getters, setters, and empty constructor.

import java.time.LocalDateTime;
// ↑ Java's date-time class. Used to store the OTP creation and expiry timestamps.

// ============================================================
// WHAT IS OtpVerification?
// This class represents the "otp_verifications" table in MySQL.
// OTP stands for One-Time Password — a short-lived code (usually 6 digits)
// sent to a user's email to verify their identity during signup.
//
// HOW OTP FLOW WORKS IN THIS APP:
//   1. User requests signup → Backend generates a 6-digit OTP and emails it.
//   2. OTP is saved in this table with an expiry time (10 minutes from now).
//   3. User enters the OTP in the app → Backend checks if it matches and isn't expired.
//   4. If valid, the user is created in the system and OTP record is deleted/marked verified.
//
// TABLE STRUCTURE:
//   otp_verifications
//   ├── id          (primary key, auto-incremented)
//   ├── email       (the email the OTP was sent to)
//   ├── name        (user's name, stored to create the User record after verification)
//   ├── otp_code    (the 6-digit code, e.g., "483920")
//   ├── created_at  (when the OTP was generated)
//   ├── expires_at  (created_at + 10 minutes — OTP is invalid after this time)
//   └── verified    (true/false — was the OTP successfully used?)
// ============================================================

@Getter        // ↑ Lombok: auto-generates getEmail(), getOtpCode(), isVerified() etc.
@Setter        // ↑ Lombok: auto-generates setEmail(), setOtpCode(), setVerified() etc.
@NoArgsConstructor  // ↑ Lombok: generates empty OtpVerification() constructor (needed by JPA)
@Entity             // ↑ JPA: this class represents a database table
@Table(name = "otp_verifications") // ↑ JPA: MySQL table name is "otp_verifications"
public class OtpVerification {
    // Note: Does NOT extend BaseEntity — it manages its own timestamps manually (createdAt, expiresAt).

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // ↑ Primary key that auto-increments (1, 2, 3...)
    private Long id;

    @Column(nullable = false)
    // ↑ email is required — we need it to know WHO this OTP belongs to.
    private String email;
    // The email address the OTP was sent to (e.g., "aryan@gmail.com").

    /** User's full name — stored during OTP request so we can create the user after verification */
    @Column(nullable = false)
    private String name;
    // The user's name entered during signup. We store it here so after OTP verification,
    // we can create the User record with the correct name.

    /** 6-digit OTP code */
    @Column(name = "otp_code", nullable = false, length = 6)
    // ↑ name = "otp_code": the column name in MySQL.
    //   nullable = false: the code is always required.
    //   length = 6: MySQL varchar column is max 6 characters long.
    private String otpCode;
    // The actual 6-digit one-time code sent to user's email (e.g., "394820").

    @Column(name = "created_at", nullable = false)
    // ↑ The time when the OTP was created and sent to the user.
    private LocalDateTime createdAt;

    /** OTP expires 10 minutes after creation */
    @Column(name = "expires_at", nullable = false)
    private LocalDateTime expiresAt;
    // The deadline after which the OTP is no longer valid.
    // Set to: createdAt + 10 minutes (see constructor below).

    /** True once the user has successfully verified this OTP */
    @Column(nullable = false)
    private boolean verified = false;
    // Starts as false. Becomes true when user successfully enters the correct OTP.

    // CUSTOM CONSTRUCTOR (not generated by Lombok):
    // When we create a new OTP, we provide email, name, and the OTP code.
    // createdAt and expiresAt are automatically calculated.
    public OtpVerification(String email, String name, String otpCode) {
        this.email     = email;                            // Store the email
        this.name      = name;                             // Store the user's name
        this.otpCode   = otpCode;                          // Store the OTP code
        this.createdAt = LocalDateTime.now();              // Set creation time to NOW
        this.expiresAt = LocalDateTime.now().plusMinutes(10); // OTP expires 10 mins from now
        this.verified  = false;                            // Starts as not verified
    }

    // METHOD: Check if this OTP has expired.
    // Returns TRUE if the current time is AFTER the expiry time.
    // Returns FALSE if the OTP is still valid.
    public boolean isExpired() {
        // LocalDateTime.now() → current time
        // this.expiresAt → deadline time
        // isAfter() → returns true if current time passed the deadline
        return LocalDateTime.now().isAfter(this.expiresAt);
    }
}
